### PR TITLE
updated syn to 2.0.52

### PR DESCRIPTION
**Pull request by happylinks**

### CODE REVIEW

**Comment by neoeinstein** [comment]
Hey @happylinks. Is there a reason that this would be required? Having a minimum of 2.0.15 means that 2.0.52 is compatible as well. This change to the `Cargo.toml` would _require_ anyone depending on 2.0.15–2.0.51 to take an update to `syn` if they were to update this package too.

**Comment by happylinks** [comment]
Ah ok, didn't realise that. 
I had a different package that required 2.0.52, and was getting an issue with aliri_braid not allowing it to be upgraded.
```
error: failed to select a version for `syn`.
    ... required by package `glib-macros v0.20.0 (https://github.com/gtk-rs/gtk-rs-core?branch=master#d9a35571)`
    ... which satisfies git dependency `glib-macros` (locked to 0.20.0) of package `glib v0.20.0 (https://github.com/gtk-rs/gtk-rs-core?branch=master#d9a35571)`
    ... which satisfies git dependency `glib` (locked to 0.20.0) of package `gstreamer v0.23.0 (https://gitlab.freedesktop.org/gstreamer/gstreamer-rs?branch=main#7f9dd587)`
    ... which satisfies git dependency `gst` (locked to 0.23.0) of package `discoverer v0.1.0 (/Users/michielwesterbeek/projects/tella-fusion/packages/core/discoverer)`
    ... which satisfies path dependency `discoverer` (locked to 0.1.0) of package `tella_fusion_lambda v0.1.0 (/Users/michielwesterbeek/projects/tella-fusion/packages/core/lambdas/fusion)`
versions that meet the requirements `^2.0.52` are: 2.0.52

all possible versions conflict with previously selected packages.

  previously selected package `syn v2.0.48`
    ... which satisfies dependency `syn = "^2.0.15"` (locked to 2.0.48) of package `aliri_braid_impl v0.4.0`
    ... which satisfies dependency `aliri_braid_impl = "=0.4.0"` (locked to 0.4.0) of package `aliri_braid v0.4.0`
    ... which satisfies dependency `aliri_braid = "^0.4.0"` (locked to 0.4.0) of package `database v0.1.0 (/Users/michielwesterbeek/projects/tella-fusion/packages/core/database)`

failed to select a version for `syn` which could resolve this conflict
```

Is there a better way to fix that, besides downgrading the other package?

**Comment by neoeinstein** [comment]
Try `cargo update -p syn --precise 2.0.52`

**Comment by happylinks** [comment]
Thanks a lot, guess it was just my lockfile being wrong! Closing this :)

**Pull request closed without merging**
