### PR TITLE
Refactor to v0.2

### LINKED ISSUE #7: Usage of borrowed form in const contexts
It would be nice to allow usage of the borrowed form of a plain wrapper in const contexts as in the following:

```
#[braid]
struct MyData;

const X: &MyDataRef = MyDataRef::from_str("test");
```

This is currently blocked by the stabilization of `const_fn_transmute`/`const_fn_union` in rust-lang/rust#85769. We can do some pre-work to verify that this will work on nightly, and then make it real when that stabilization patch lands.

### LINKED ISSUE #9: no way to put proc-attributes on borrowed type
```rust
// run cargo doc with `RUSTDOCFLAGS="--cfg nightly"`
#![feature(doc_cfg)]
use aliri_braid::braid;

#[braid]
#[cfg(any(docs, feature = "thing"))]
#[cfg_attr(nightly, doc(cfg(feature = "thing")))]
struct Thing;
```

above example will put a cfg and doc_cfg on `Thing`, but not on `ThingRef`.
This results in some wierd state for documentation, for example, docs will be (from real example)
image

I'd want to be able to put a `#[doc(cfg(...))]` on the `Ref` as well.

### LINKED ISSUE #10: Add `from_static()` creation functions
Add `from_static(&'static str) -> Self` functions to the owned and borrowed forms. On validated/normalized forms, `from_static` should panic if the value is not valid (or not normalizable, in the case of a owned normalized value)

### LINKED ISSUE #11: Provide an implementation of Ord/PartialOrd
Because storing braids in `BTreeMap`/`BTreeSet` is cool.

The other option is to make sure its relatively easy to put `#[derive(Ord, PartialOrd)]` on both the owned and borrowed forms.

### LINKED ISSUE #12: Allow using Bytes
Currently only `String` is usable as the wrapped type. It would be nice to allow the wrapped type to be a constrained generic or, in particular, `Bytes`.

### PR DESCRIPTION
**Pull request by neoeinstein**
This update looks to improve the API definitions a bit:

# Breaking changes
* Reducing some excess generic-ness on `Owned::new()`, which now always takes `String`
* Add more ergonomic `Borrowed::from_static(&'static str)`, which panics for invalid fallible/normalized values, less `unwrap()`-ing in tests/startup code
  * Closes #10
* Add impls of `Ord` and `PartialOrd`
  * Closes #11
* Rename `omit_clone`, `debug_impl`, `display_impl` parameters
  * Now `clone`, `debug`, and `display`, respectively
* Add `impl From<Owned> for Arc<Borrowed>` and `impl From<Owned> for Rc<Borrowed>`
* Remove trait bound that requires `Normalizer/Validator::Error` implements `StdError + Send + Sync`
* Remove blanket `impl<T> Validator for T where T: Normalizer`
  * `Normalizer` is now a subtrait of `Validator` and inherits the error type from `Validator`.
  * This allows validator to be implemented more efficiently
  * Does require that validator ensure the value is _already_ in normalized form to preserve invariants
* Remove a few extra impls of `PartialEq`

# New features
* Add means to add attributes to just the owned type, just the borrowed type, or both
  * Closes #9
* Types now implement `StructuralEq` and `StructuralPartialEq`, potentially enabling const pattern matching
  * See #8 for issues with pattern matching
* Constify things a bit more
  * Closes #7
* Now possible to wrap more types than just `std::string::String`
  * In particular, now can use `smartstring::SmartString` as an inner type
  * Thanks to the release of `bytestring` v1.1.0, can also use `bytestring::ByteString`
    * Closes #12
  * Examples includes an example of a minimal usable string type
* Now possible to use braids in `#![no_std]` crates using `no_std` macro parameter (requires `alloc`).
* `aliri_braid` crate itself is now `no_std`. Use of `Normalizer` requires the `alloc` feature (enabled by default).
* `#[braid_ref]` is back, allowing creation of ref-only braids. Compatible with `#![no_std]` without `alloc`.

cc: @emilgardis as another primary consumer of this crate

### CODE REVIEW

**Comment by Emilgardis** [comment]
Looks good!

I have one concern with the PartialOrd impl, it'd be good if it was possible to override it. Use case is a `Timestamp` braid, where some comparisons are not valid.

**Comment by neoeinstein** [comment]
> I have one concern with the PartialOrd impl, it'd be good if it was possible to override it.

I can add in a macro parameter `ord`, which defaults to `impl`, but could be `owned` or `none` as desired, similar to the parameters controlling `Debug` and `Display` (which I use to provide [data hiding implementations in `aliri`](https://docs.rs/aliri/latest/aliri/struct.JwtRef.html#impl-Display)).

My primary impetus for beginning to implement `Ord` was to make braids eligible for use as keys in a `BTreeMap`/`BTreeSet` without too much fuss, just like they already do for `HashMap`/`HashSet`.

**Comment by Emilgardis** [comment]
awesome! I'm happy with this so far

**Comment by Emilgardis** [comment]
Ah, the readme on github and crates.io does not accept the intra-doc links, so it looks wierd

**Comment by neoeinstein** [comment]
Silly me. I’ll do a quick point release that fixes those.

**Pull request merged**
